### PR TITLE
Update template_shelly_monitoring.yaml

### PR DESCRIPTION
**Pull request by UniverseDevel**
Updated version of template

### CODE REVIEW

**Comment by UniverseDevel** [comment]
README seems to be somehow autogenerated, What is the correct way to update this (I haven't seen or might have missed info about READMEs in guideline)? Overview seems to be copied multiple times in this README and tables that are autogenerated might be out of date as well, but I don't think I will go trough them and manually fix them all, I don't have that much free time.

**Comment by RogerTheUnicornHive** [comment]
Hello @UniverseDevel,
The readme is indeed automatically generated, and will be updated on successful pull request when CI/CD will run.

**Comment by UniverseDevel** [comment]
Great then how to update just the Overview section of it?

**Comment by oscar120584** [comment]
Hello @UniverseDevel,
OverView Section is copied from the template description field. If you wish, you can use MarkDown formatting.

**Comment by UniverseDevel** [comment]
Fantastic, I will later update my templates description. Thank you

**Pull request merged**
