### PR TITLE
Add Gitlab Update Check template

### PR DESCRIPTION
**Pull request by PackeTsar**
I've added a template and external check script which allows Zabbix to query a Gitlab instance to see if it has outstanding updates which need to be installed. If there are updates available, Zabbix will trigger a problem and alert the user.

### CODE REVIEW

**Comment by oscar120584** [comment]
We wanted to thank you for your contribution to the development of the community, but we can't take your PR. Please add a directory with a version.
Example:
template_gitlab_update_check
    \_5.0
    |   \_zabbix_template_gitlab_update_check.xml
    |   |_README.md
    |   |_gitlab_update_check.sh
    |_...

**Comment by PackeTsar** [comment]
Yea I can definitely do that!

**Comment by PackeTsar** [comment]
OK how does this look?

**Comment by PackeTsar** [comment]
OK I think the folder structure is correct now

**Pull request merged**
