### PR TITLE
Added template Intelbras NVR version 700 and updated Readme

### PR DESCRIPTION
**Pull request by diasdmhub**
## Added template Intelbras NVR version 700 and updated Readme

- **Updated template to `Zabbix 7.0 LTS`**
---
- Updated template name to include Dahua
- Updated camera status item to numeric type to take advantage of thresholds
- Updated camera status trigger expression
- Updated some tags
- Updated some item names
- Updated the template dashboard to include better widgets (prototypes are **not** supported with new widgets)
---
- Added discovery `Disable lost resources` period
- Added `Camera Availability` value mapping

### CODE REVIEW

**Comment by diasdmhub** [comment]
> Pre-release for Zabbix 7.0-1

## Highly optimized SNMP monitoring.

### Refactored data collection to SNMP Walk to take advantage of SNMP poller and item dependency

---

⚠️ **This template update may clear some items history**

⚠️ **Custom dashboard items should be updated**

---

- Added the master item `Device Walk System Info`
- Added the master item `Device Walk System General`
- Added the master item `Device Walk Network`
- Added the master item `Device Walk Storage`
- Added the master item `Device Walk Remote Cam`
- Added the dependent item `Memory Total`
- Added the trigger `Unresponsive Web Port`

---

- Removed the item `System object ID` as the vendor object identification is not referenced

---

- Changed most items to dependent ones
- Changed discoveries to dependent ones
- Changed some item keys to make them similar to MIB
- Changed `Memory Utilization` item to `Numeric (unsigned)` type of information
- Changed `Disk Status` item to numeric with mapped values
- Changed `Disk Utilization` item calculation. It now shows the utilization percentage
- Changed expression of `Disk ERROR` trigger
- Changed the default value of macro `{$DISK_FREE_WARN}` to 100. This way, the disk utilization trigger is ignored.

---

- Updated inventory item data
- Updated most objects descriptions
- Updated some minor names
- Updated some minor tags

**Comment by diasdmhub** [comment]
Merged the pre-release 701 into main.

**Comment by igorbach** [comment]
Hello!
Zabbix community templates project is an international one, so, please, translate all content into English

**Comment by diasdmhub** [comment]
> Hello! Zabbix community templates project is an international one, so, please, translate all content into English

Hi.
Thanks for your input.

The template is completely english.
All items, triggers, graphs, etc. are english. Only descriptions are bilingual.

As for the template's `README`, it is fully bilingual, just like the one currently published in this repository.

All content has english translations line by line.
I hope this is enough.

Thank you.

**Pull request closed without merging**
