### PR TITLE
I made a template for HP Color Laserjet CP1515n printer

### PR DESCRIPTION
**Pull request by hlovdal**
I copied the existing CP2025dn template and modified it to match CP1515n, including changing all the relevant uuids in the yaml file. For the last point I wrote a python script to do those changes automatically.

This branch is made on top of the branch in [this pull request](https://github.com/zabbix/community-templates/pull/5), I will rebase this branch when that pull request is merged to `main`.

### CODE REVIEW

**Comment by oscar120584** [comment]
We wanted to thank you for your contribution to the development of the community, but we can't take your PR. Please, correct the directory structure.
Example:
>template_name

    \_5.0
    |   \_template_<name>.xml
    |   |_README.md
    |   |_files
    |       \_other_files
    |       |_ ...
    |_5.4
    |   \_template_<name>.[xml,yaml,json]
    |   |_README.md
    |   |_files
    |       \_other_files
    |       |_ ...
    |
    |_...
All additional files: executable external check scripts, images, auxiliary utilities, third-party integration - must be moved to the "files" directory

**Comment by hlovdal** [comment]
The python script is not bound to this pull request at all and should not live inside `template_hp_color_laserjet_cp1515n`. I moved it out to a separate [pull request](https://github.com/zabbix/community-templates/pull/15).

**Comment by oscar120584** [comment]
It is very important that the version in the name of the catalog coincides with the actual version of the template. For example, in the 5.0 directory there must be a template for version 5.0.

**Comment by hlovdal** [comment]
What do you mean? The directory already follows exactly that structure:

```bash
$ tree template_hp_color_laserjet_cp1515n 
template_hp_color_laserjet_cp1515n
├── 5.0
│   ├── README.md
│   └── template_hp_color_laserjet_cp1515n.xml
└── 5.4
    ├── README.md
    └── template_hp_color_laserjet_cp1515n.yaml
$
```

I have just re-tested importing and then exporting again against one 5.0 and one 5.4 server, and sans timestamp and space vs tab for indentation the exported files are the same as the files checked into git. I cannot see anything that is wrong or missing with these template files.

**Comment by oscar120584** [comment]
Yes, all right. Thanks for the integration.

**Pull request merged**
