### PR TITLE
Template Synology HyperBackup

### PR DESCRIPTION
**Pull request by gianlucaromito**
Hello I've made and interesting template to get pull information from  Synology Hyperbackup to Zabbix. I think it is really useful for many people.

### CODE REVIEW

**Comment by oscar120584** [comment]
We wanted to thank you for your contribution to the development of the community, but we can't take your PR. Please correct the directory structure.
Example:
>template_name

    \_5.0
    |   \_template_<name>.xml
    |   |_README.md
    |   |_files
    |       \_other_files
    |       |_ ...
    |_5.4
    |   \_template_<name>.[xml,yaml,json]
    |   |_README.md
    |   |_files
    |       \_other_files
    |       |_ ...
    |
    |_...

**Comment by gianlucaromito** [comment]
Hi thanks for checking.
I've changed the dir structure as requested.
Let me know.
Gianluca

**Comment by oscar120584** [comment]
It is very important that the version in the name of the catalog coincides with the actual version of the template. For example, in the 5.0 directory there must be a template for version 5.0.

**Comment by gianlucaromito** [comment]
ok removed the 5.0 version.

**Pull request merged**
