### PR TITLE
New template for RavenDB

### PR DESCRIPTION
**Pull request by hiddenshadow21**
Template for monitoring RavenDB server using SNMP.

### CODE REVIEW

**Comment by igorbach** [comment]
Hello!
Please, change the author name from `RavenDB` to yourself for easy maintenance in future

**Comment by gregolsky** [comment]
@igorbach We updated the authors. Anything else we need to do?

**Comment by igorbach** [comment]
@gregolsky, there is a content error. You've provided the template_ravendb_server.yaml file, but it's file content is JSON.
It is confusing and leads to import error. 
Yaml is unified format for all out modern tempaltes as well
Please, provide the correct template file

**Comment by gregolsky** [comment]
@igorbach Thank you for letting us know. We fixed the file. Is there anything else remaining please?

**Review by gregolsky — APPROVED** [review]

**Comment by gregolsky** [comment]
Please approve the workflow run.

**Comment by gregolsky** [comment]
can we merge this please?

**Pull request merged**
