### PR TITLE
VMmanager 6

### PR DESCRIPTION
**Pull request by usaafko**
Add template for VMmanager 6 monitoring

https://www.ispsystem.com/software/vmmanager

### CODE REVIEW

**Comment by oscar120584** [comment]
We wanted to thank you for your contribution to the community development, but we cannot take your PR. Please correct the directory structure. Examples are available in the [documentation](https://www.zabbix.com/documentation/guidelines/en/thosts/community_templates). It is not necessary to reduce templates for all versions from Example (5.0, 5.4). It is also very important that the version in the catalog name coincided with the actual version of the template. For example, in the 5.0 directory, there must be a template for version 5.0.

**Comment by usaafko** [comment]
Hello, thank you for your feedback. Could you help me to fix that?

1. I need to remove number 6 from template name? How can I create template only for 6 version of VMmanager?
2. If not - I need to remove 5.0 directories? My zabbix template was generated by 5.4 version, but: I created templates in 5.0 version and update it to 5.4 (to add new user features)

**Comment by oscar120584** [comment]
Hello.
Yes, it is enough to delete the 5.0 directory. Server version 5.0 will not be able to import a template generated by more new versions (5.2 and higher)

**Comment by usaafko** [comment]
Ok, it's done. Thank you

**Pull request merged**
